Error from server (AlreadyExists): deployments.apps "upfour" already exists
NAME                      READY   STATUS    RESTARTS   AGE
upfour-56968cb9dc-ljbtf   1/1     Running   0          67m
sleeping for 10 secondss while waiting for pod to come up
Error from server (AlreadyExists): services "upfour" already exists
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000

^C/usr/local/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from version 0.20.3 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/local/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.20.3 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator GradientBoostingRegressor from version 0.20.3 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
 * Debugger is active!
 * Debugger PIN: 194-414-639

{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2020-01-27 21:14:19,093] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-01-27 21:14:19,109] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-01-27 21:14:19,115] INFO in app: Prediction Returned Log:: 
[20.35373177134412]
127.0.0.1 - - [27/Jan/2020 21:14:19] "POST /predict HTTP/1.1" 200 -

